[[pages]]
path = "smartrx_web/smartrx.py"
name = "Welcome to SmartRx!!!"
icon = "ğŸ¥"

[[pages]]
path = "smartrx_web/news.py"
name = "Daily News"
icon = "ğŸŒ"

[[pages]]
path = "smartrx_web/check_ddi.py"
name = "Drug-Drug Interaction Check"
icon = "ğŸ’Š"

[[pages]]
path = "smartrx_web/check_dfi.py"
name = "Drug-Food Interaction Check"
icon = "ğŸ²"

[[pages]]
path = "smartrx_web/drug_list.py"
name = "Drug List"
icon = "ğŸ“œ"

[[pages]]
path = "smartrx_web/about.py"
name = "About"
icon = "â„¹ï¸"

[[pages]]
path = "smartrx_web/contact.py"
name = "Contact"
icon = "ğŸ“§"