[[pages]]
path = "smartrx_web/smartrx.py"
name = "Welcome to SmartRx!!!"
icon = "ğŸ¥"

[[pages]]
path = "smartrx_web/news.py"
name = "Tin thá»©c thÆ°á»ng ngÃ y"
icon = "ğŸŒ"

[[pages]]
path = "smartrx_web/check_ddi.py"
name = "Kiá»ƒm tra tÆ°Æ¡ng tÃ¡c Thuá»‘c - Thuá»‘c"
icon = "ğŸ’Š"

[[pages]]
path = "smartrx_web/check_dfi.py"
name = "Kiá»ƒm tra tÆ°Æ¡ng tÃ¡c Thuá»‘c - Thá»±c pháº©m"
icon = "ğŸ²"

[[pages]]
path = "smartrx_web/drug_list.py"
name = "Danh sÃ¡ch thuá»‘c"
icon = "ğŸ“œ"

[[pages]]
path = "smartrx_web/about.py"
name = "ThÃ´ng tin"
icon = "â„¹ï¸"

[[pages]]
path = "smartrx_web/contact.py"
name = "LiÃªn há»‡"
icon = "ğŸ“§"